layout_spectrum: 0.9408754804171622
typography_spectrum: 0.0023577872198075056
color:
  saturation: 0.40600319392979145
  lightness: 0.5636395323090255
  brandStrength: 0.6267227644566447
  brandColors:
    - '#FFFFFF'
    - '#36A5DD'
    - '#FBD504'
    - '#000000'
    - '#646464'
  rhythmicContrast: 0.16559665114618838
author:
  name: Frank Ozoria Jr
  email: Frank.ozoria@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9a1f0d96-f51e-4ede-bb00-cf691ec94f38.jpg
name: Tomotheapp.com
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/919e1746-05a0-4632-bd59-2b48b8278928.jpg
title: TOMO!
description: Your First Step Toward Social Pollination
