typography_spectrum: 0.9121864
color:
  saturation: 0.7724015
  lightness: 0.7096774
  brandStrength: 0.7876315
  brandColors:
    - '#000000'
    - '#FFD700'
    - '#827021'
    - '#D3BD29'
    - '#615015'
  rhythmicContrast: 0.5670069
layout_spectrum: 0
author:
  name: Frank Ozoria Jr
  email: Frank.ozoria@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9a1f0d96-f51e-4ede-bb00-cf691ec94f38.jpg
name: Tomotheapp.com
title: Your First Step Toward Social Pollination
description: Your First Step Toward Social Pollination
